### ISSUE TITLE
您好，编译不成功，少文件

### ISSUE THREAD

**Issue by lianyitj** [tower1229/Vue-Scaffold#11]
These relative modules were not found:

* ./views/Login.vue in ./src/common/index.js
* ./views/Index in ./src/main/index.js

**Comment by lianyitj** [comment]
找到原因了，首字母写成大写了，所以找不到

**Comment by tower1229** [comment]
> 找到原因了，首字母写成大写了，所以找不到

如果基于原来的版本更新会出现这个问题，全新拉取的话应该没问题

**Comment by lianyitj** [comment]
不过我确实是全新拉取的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tower1229/Vue-Scaffold"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 中午1:45
收件人:&nbsp;"tower1229/Vue-Scaffold"<Vue-Scaffold@noreply.github.com&gt;;
抄送:&nbsp;"廉毅"<lian_yi2008@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [tower1229/Vue-Scaffold] 您好，编译不成功，少文件 (#11)





  
找到原因了，首字母写成大写了，所以找不到
  
如果基于原来的版本更新会出现这个问题，全新拉取的话应该没问题

**Comment by tower1229** [comment]
> 不过我确实是全新拉取的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "tower1229/Vue-Scaffold" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月12日(星期二) 中午1:45 收件人:&nbsp;"tower1229/Vue-Scaffold"<Vue-Scaffold@noreply.github.com&gt;; 抄送:&nbsp;"廉毅"<lian_yi2008@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [tower1229/Vue-Scaffold] 您好，编译不成功，少文件 (#11) 找到原因了，首字母写成大写了，所以找不到 如果基于原来的版本更新会出现这个问题，全新拉取的话应该没问题 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

现在可以了，因为我本地没有配置git大小写敏感，所以没有正确同步个别文件

**Comment by lianyitj** [comment]
好的，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tower1229/Vue-Scaffold"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 中午1:57
收件人:&nbsp;"tower1229/Vue-Scaffold"<Vue-Scaffold@noreply.github.com&gt;;
抄送:&nbsp;"廉毅"<lian_yi2008@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [tower1229/Vue-Scaffold] 您好，编译不成功，少文件 (#11)





  
不过我确实是全新拉取的
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "tower1229/Vue-Scaffold" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月12日(星期二) 中午1:45 收件人:&nbsp;"tower1229/Vue-Scaffold"<Vue-Scaffold@noreply.github.com&gt;; 抄送:&nbsp;"廉毅"<lian_yi2008@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [tower1229/Vue-Scaffold] 您好，编译不成功，少文件 (#11) 找到原因了，首字母写成大写了，所以找不到 如果基于原来的版本更新会出现这个问题，全新拉取的话应该没问题 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
现在可以了，因为我本地没有配置git大小写敏感，所以没有正确同步个别文件
