### ISSUE TITLE
登录时提示网络异常

### ISSUE THREAD

**Issue by lianyitj** [tower1229/Vue-Scaffold#12]
如题，
估计和定位到这个地址有关系：POST http://ysxt.kaifa/japi/login net::ERR_NAME_NOT_RESOLVED，
既然开源了，希望咱能处理得好一些啊，谢谢！

**Comment by tower1229** [comment]
已将默认请求切换到基于rap2.taobao的mock接口

**Comment by lianyitj** [comment]
哦，刚学vue，不太会用，别见笑啊。。。包括您的在线演示网址也报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tower1229/Vue-Scaffold"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 中午1:48
收件人:&nbsp;"tower1229/Vue-Scaffold"<Vue-Scaffold@noreply.github.com&gt;;
抄送:&nbsp;"廉毅"<lian_yi2008@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tower1229/Vue-Scaffold] 登录时提示网络异常 (#12)





 
已将默认请求切换到基于rap2.taobao的mock接口

**Comment by tower1229** [comment]
> 哦，刚学vue，不太会用，别见笑啊。。。包括您的在线演示网址也报错
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "tower1229/Vue-Scaffold" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月12日(星期二) 中午1:48 收件人:&nbsp;"tower1229/Vue-Scaffold"<Vue-Scaffold@noreply.github.com&gt;; 抄送:&nbsp;"廉毅"<lian_yi2008@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [tower1229/Vue-Scaffold] 登录时提示网络异常 (#12) 已将默认请求切换到基于rap2.taobao的mock接口 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

演示网址报错是因为rap2不支持https请求，在自己电脑上运行没问题的

**Comment by lianyitj** [comment]
哦，那请问在本机上怎么改呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tower1229/Vue-Scaffold"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 下午2:18
收件人:&nbsp;"tower1229/Vue-Scaffold"<Vue-Scaffold@noreply.github.com&gt;;
抄送:&nbsp;"廉毅"<lian_yi2008@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tower1229/Vue-Scaffold] 登录时提示网络异常 (#12)





  
哦，刚学vue，不太会用，别见笑啊。。。包括您的在线演示网址也报错
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "tower1229/Vue-Scaffold" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月12日(星期二) 中午1:48 收件人:&nbsp;"tower1229/Vue-Scaffold"<Vue-Scaffold@noreply.github.com&gt;; 抄送:&nbsp;"廉毅"<lian_yi2008@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [tower1229/Vue-Scaffold] 登录时提示网络异常 (#12) 已将默认请求切换到基于rap2.taobao的mock接口 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
演示网址报错是因为rap2不支持https请求，在自己电脑上运行没问题的
