### ISSUE TITLE
多个模块中如果使用不同的baseurl可以如何处理？

### ISSUE THREAD

**Issue by 52imnet** [tower1229/Vue-Scaffold#4]
比如在有A B 两个模块，A中使用的是bai.com/  B模块请求的接口使用的是api.xxx.com 

请问下这种场景下，api 里面应该如何区分才行？ 感谢

**Comment by tower1229** [comment]
那就每个模块管理自己的axios实例，全局的api就不需要了，相当于每个模块都有一个自己的api.js
